apiVersion: v1
kind: Pod
metadata:
  name: example-app
selector:
  matchLabels:
    app: example-app
spec:
  containers:
  - name: example-app
    image: bahqiplor/cinq-gitops-workshop:latest
    ports:
    - containerPort: 5000
